name: ‚§µÔ∏è Update submodules

on:
  workflow_call:
  schedule:
    - cron: '0 3 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: üì• Fetch Repository Contents
        uses: actions/checkout@main

      - name: ‚¨áÔ∏è Update submodules recursively
        shell: bash
        run: |
          git submodule update --rebase --remote

      - name: ‚¨ÜÔ∏è Commit and push changes
        shell: bash
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "Update submodules" || true
          git push origin master
